# Generated by Django 2.2.28 on 2022-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('userpasswd', models.CharField(max_length=32)),
                ('register_time', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
